### PR TITLE
add ubuntu wildcard

### PR DESCRIPTION
**Pull request by shansri**
## Description

_Describe the changes needed_

### CODE REVIEW

**Review by shansri — COMMENTED** [review]
reviewed

**Review by shanmugamsridharan — APPROVED** [review]

**Comment by shanmugamsridharan** [comment]
reviewed

**Comment by shanmugamsridharan** [comment]
reviewed

**Review by shanmugamsridharan — APPROVED** [review]

**Comment by shanmugamsridharan** [comment]
done

**Review by shanmugamsridharan — APPROVED** [review]

**Comment by shanmugamsridharan** [comment]
completed

**Review by shanmugamsridharan — APPROVED** [review]
approved

**Review by shanmugamsridharan — COMMENTED** [review]
review

**Comment by shanmugamsridharan** [comment]
review

**Pull request closed without merging**
