### PR TITLE
add ubuntu wildcard

### PR DESCRIPTION
**Pull request by rnxrx-a**
added ubuntu domain to filter to allow apt update/upgrade to work

## Description

_Describe the changes needed_

### CODE REVIEW

**Comment by rnxrx-a** [comment]
support for apt update/upgrade via ubuntu domain

**Comment by rnxrx-g** [comment]
ok security

**Comment by rnxrx** [comment]
netops ok

**Review by rnxrx — APPROVED** [review]

**Review by rnxrx-g — APPROVED** [review]
ok sec ops

**Review by rnxrx-g — APPROVED** [review]

**Review by rnxrx — APPROVED** [review]

**Review by rnxrx-g — APPROVED** [review]

**Review by rnxrx — APPROVED** [review]

**Pull request closed without merging**
